Repository BCSDLab/JJBAKSA_BACK_END, pull requests merged in 2022-09, with the labels that each got.

#23 fix: swagger에서 이미지 파일 업로드할 수 있도록 변경
  src/main/java/com/jjbacsa/jjbacsabackend/image/serviceImpl/ImageServiceImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/controller/ReviewController.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/dto/request/ReviewModifyRequest.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/dto/request/ReviewModifyRequestDto.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/dto/request/ReviewRequest.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/dto/request/ReviewRequestDto.java
Labels: bug

#22 [jb-002] 회원가입, 로그인
  build.gradle
  src/main/java/com/jjbacsa/jjbacsabackend/etc/config/SecurityConfig.java
  src/main/java/com/jjbacsa/jjbacsabackend/etc/dto/Token.java
  src/main/java/com/jjbacsa/jjbacsabackend/etc/enums/TokenType.java
  src/main/java/com/jjbacsa/jjbacsabackend/etc/enums/UserType.java
  src/main/java/com/jjbacsa/jjbacsabackend/etc/filter/JwtTokenFilter.java
  src/main/java/com/jjbacsa/jjbacsabackend/etc/interceptor/AuthInterceptor.java
  src/main/java/com/jjbacsa/jjbacsabackend/etc/security/CustomAccessDeniedHandler.java
  src/main/java/com/jjbacsa/jjbacsabackend/etc/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/jjbacsa/jjbacsabackend/etc/security/JwtTokenProvider.java
  src/main/java/com/jjbacsa/jjbacsabackend/user/controller/UserController.java
  src/main/java/com/jjbacsa/jjbacsabackend/user/entity/CustomUserDetails.java
  src/main/java/com/jjbacsa/jjbacsabackend/user/service/UserService.java
  src/main/java/com/jjbacsa/jjbacsabackend/user/serviceImpl/UserDetailsServiceImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/user/serviceImpl/UserServiceImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/util/JwtUtil.java
  src/test/java/com/jjbacsa/jjbacsabackend/user/service/UserServiceTest.java
Labels: feature

#24 hotfix: 코드 유실점 발견
  src/main/java/com/jjbacsa/jjbacsabackend/image/serviceImpl/ImageServiceImpl.java
Labels: bug

#20 [jb-008] 스크랩
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/controller/ScrapController.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/dto/ScrapDirectoryRequest.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/dto/ScrapDirectoryResponse.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/dto/ScrapRequest.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/dto/ScrapResponse.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/entity/ScrapDirectoryCount.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/entity/ScrapDirectoryEntity.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/entity/ScrapEntity.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/mapper/ScrapDirectoryMapper.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/mapper/ScrapMapper.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/repository/DslScrapDirectoryRepository.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/repository/DslScrapDirectoryRepositoryImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/repository/DslScrapRepository.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/repository/DslScrapRepositoryImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/repository/ScrapDirectoryRepository.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/repository/ScrapRepository.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/service/ScrapService.java
  src/main/java/com/jjbacsa/jjbacsabackend/scrap/service/ScrapServiceImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/user/entity/UserCount.java
  src/main/java/com/jjbacsa/jjbacsabackend/util/CursorUtil.java
  src/main/resources/db/migration/V2__create.sql
  src/test/java/com/jjbacsa/jjbacsabackend/scrap/repository/ScrapRepositoryTest.java
  src/test/java/com/jjbacsa/jjbacsabackend/scrap/service/ScrapServiceTest.java
Labels: feature

#28 [jb-006] 리뷰 조회 api 추가 및 테스트 db 분리
  build.gradle
  src/main/java/com/jjbacsa/jjbacsabackend/image/serviceImpl/ImageServiceImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/controller/ReviewController.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/dto/request/ReviewModifyRequest.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/dto/request/ReviewRequest.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/dto/response/ReviewDeleteResponse.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/dto/response/ReviewResponse.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/entity/ReviewEntity.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/repository/querydsl/DslReviewRepository.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/repository/querydsl/DslReviewRepositoryImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/service/ReviewService.java
  src/main/java/com/jjbacsa/jjbacsabackend/review/serviceImpl/ReviewServiceImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/shop/entity/ShopCount.java
  src/main/resources/application.yml.sample
  src/main/resources/db/migration/V3__modify_review_table.sql
  src/main/resources/db/test/test_insert.sql
  src/test/java/com/jjbacsa/jjbacsabackend/review/service/ReviewServiceTest.java
Labels: enhancement, feature
