Repository BCSDLab/JJBAKSA_BACK_END, pull requests merged in 2024-01, with the labels that each got.

#144 Feat: 이름 랜덤 설정 기능 추가
  src/main/java/com/jjbacsa/jjbacsabackend/user/serviceImpl/UserServiceImpl.java
  src/main/java/com/jjbacsa/jjbacsabackend/util/NameUtil.java
Labels: feature

#146 feat: bootJar 설정 추가
  build.gradle
Labels: enhancement

#149 fix: add swagger config
  src/main/java/com/jjbacsa/jjbacsabackend/etc/config/SwaggerPathResolver.java
  src/main/resources/application.yml.sample
Labels: documentation
